export const mockEvent = [
  {event: 'start', data: ''},
  {event: 'message', data: ''},
  {event: 'message', data: ''},
  {event: 'message', data: ''},
  {event: 'progress', data: '11'},
  {event: 'message', data: ''},
  {event: 'message', data: ''},
  {event: 'progress', data: '21'},
  {event: 'message', data: ''},
  {event: 'progress', data: '31'},
  {event: 'message', data: ''},
  {event: 'progress', data: '52'},
  {event: 'message', data: ''},
  {event: 'progress', data: '72'},
  {event: 'message', data: ''},
  {event: 'progress', data: '90'},
  {event: 'message', data: ''},
  {event: 'success', data: 'https://picit-usercontent.ktlab.io/ai_0195e2c8-754e-7594-bbe9-77b6f919d3f6'},
  {event: 'end', data: 'stop'},
]